apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb-ns
  labels:
    app: mongodb
    role: database
spec:
  selector:
    app: mongodb
    role: database
  type: ClusterIP  
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
