apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
  namespace: backoffice-ns
  labels:
    app: backoffice
    role: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice
      role: application
  template:
    metadata:
      labels:
        app: backoffice
        role: application
    spec:
      containers:
        - name: backoffice
          image: danielsanchez18/backoffice-prueba-sistemas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_PORT
              value: "5000"
            - name: FLASK_HOST
              value: "backoffice"
            - name: MONGO_HOST
              value: "mongodb.mongodb-ns"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_DB
              value: user
            - name: REDIS_HOST
              value: "redis.redis-ns"
            - name: REDIS_PORT
              value: "6379"
            - name: ES_HOST
              value: "elasticsearch.elasticsearch-ns"
            - name: ES_PORT
              value: "9200"
            - name: ES_SCHEME
              value: "http"
            - name: ES_INDEX
              value: "user"
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /livez
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}