apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch-ns
  labels:
    app: elasticsearch
    role: database
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
    role: database
  clusterIP: None