apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backoffice-pre-ns

resources:
  - ../../../base/backoffice
  - namespace.yaml

patches:
  - path: deployment.yaml
  - path: ingress.yaml
  - path: secret.yaml
