apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mongodb
    repo: https://charts.bitnami.com/bitnami
    version: 16.4.0
    releaseName: mongodb
    namespace: mongodb-pre-ns
    valuesFile: values.yaml