apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 20.6.3
    releaseName: redis
    valuesFile: values.yaml
