apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-ns
  labels:
    app: redis
    role: database
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: database
  clusterIP: None