apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backoffice
          env:
            - name: MONGO_HOST
              value: mongodb-headless.mongodb-pre-ns
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: REDIS_HOST
              value: "redis-headless.redis-pre-ns"
            - name: ES_HOST
              value: "bd-elasticsearch-master-headless.elasticsearch-pre-ns"
            
            