apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: ingress-nginx
  chartRepoUrl: https://kubernetes.github.io/ingress-nginx
  chartVersion: 4.7.1
  releaseName: ingress-nginx
  values: values.yaml

resources:
  - namespace.yaml

namespace: ingress-nginx