architecture: replicaset   

replicaCount: 1

resources:
  requests:
    memory: "2Gi"
    cpu: "500m"
  limits:
    memory: "5Gi"
    cpu: "2"

persistence:
  enabled: true
  storageClass: "standard"
  size: 10Gi

auth:
  enabled: true
  rootUser: "mongo"  
  rootPassword: "password"
  usernames: ["mongo"]  
  passwords: ["password"]  
  databases: ["user"]    

arbiter:
  enabled: false